esphome:
  name: temp-hum
  platform: ESP8266
  board: nodemcuv2

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  password: !include ota-pw.yaml

wifi:
  networks: !include hrh.yaml

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Temp-Hum Fallback Hotspot"
    password: !include ap-pw.yaml

captive_portal:

sensor:
  - platform: dht
    pin: D2
    model: DHT22
    temperature:
      name: "Living Room Temperature"
      filters:
        - offset: -0.4
    humidity:
      name: "Living Room Humidity"
      filters:
        - offset: -12.0
    update_interval: 60s
