esphome:
  name: weather
  platform: ESP8266
  board: nodemcuv2

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  password: !include ota-pw.yaml

wifi:
  networks: !include hrh.yaml

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Weather Fallback Hotspot"
    password: !include ap-pw.yaml

captive_portal:

i2c:
  sda: D1
  scl: D2
  scan: true

sensor:
  - platform: bme280
    temperature:
      name: "BME280 Temperature"
      oversampling: 16x
    pressure:
      name: "BME280 Pressure"
    humidity:
      name: "BME280 Humidity"
    address: 0x77
    update_interval: 1s

# Battery connected, so we want to sleep a lot
#deep_sleep:
#  run_duration: 10s
#  sleep_duration: 120s
#  id: deep_sleep_1

# Don't deepsleep when OTA is attempted
#mqtt:
#  on_message:
#    - topic: weather/ota_mode
#      payload: 'ON'
#      then:
#        - deep_sleep.prevent: deep_sleep_1
#    - topic: weather/sleep_mode
#      payload: 'ON'
#      then:
#        - deep_sleep.enter: deep_sleep_1
